[package]
name = "zg-reth-exex-template"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"
license = "MIT OR Apache-2.0"

[dependencies]
# reth
reth = { version = "= 1.8.1" }
reth-ethereum = { version = "= 1.8.1", features = ["full"] }
reth-chainspec = { version = "= 1.8.1" }
reth-ethereum-cli = { version = "= 1.8.1" }
reth-discv5 = { version = "= 1.8.1" }
reth-execution-errors = { version = "= 1.8.1" }
reth-execution-types = { version = "= 1.8.1" }
reth-exex = { version = "= 1.8.1", features = ["serde"] }
reth-eth-wire = { version = "= 1.8.1" }
reth-evm = { version = "= 1.8.1" }
reth-network = { version = "= 1.8.1", features = ["test-utils"] }
reth-network-api = { version = "= 1.8.1" }
reth-network-peers = { version = "= 1.8.1" }
reth-node-api = { version = "= 1.8.1" }
reth-node-ethereum = { version = "= 1.8.1" }
reth-primitives = { version = "= 1.8.1" }
# reth-primitives-traits = { version = "= 1.8.1" }
reth-provider = { version = "= 1.8.1" }
reth-revm = { version = "= 1.8.1" }
reth-transaction-pool = { version = "= 1.8.1" }
reth-tracing = { version = "= 1.8.1" }

# revm
revm = { version = "= 29.0.1", default-features = false }
revm-bytecode = { version = "= 6.2.2", default-features = false }
revm-database = { version = "= 7.0.5", default-features = false }
revm-state = { version = "= 7.0.5", default-features = false }
revm-primitives = { version = "= 20.2.1", default-features = false }
revm-interpreter = { version = "= 25.0.3", default-features = false }
revm-inspector = { version = "= 10.0.1", default-features = false }
revm-context = { version = "= 9.1.0", default-features = false }
revm-context-interface = { version = "= 10.2.0", default-features = false }
revm-database-interface = { version = "= 7.0.5", default-features = false }
op-revm = { version = "= 10.1.0", default-features = false }

alloy-evm = { version = "= 0.21.1", default-features = false }

# alloy
alloy-consensus = { version = "= 1.0.35", default-features = false }
alloy-contract = { version = "= 1.0.35", default-features = false }
alloy-eips = { version = "= 1.0.35", default-features = false }
alloy-genesis = { version = "= 1.0.35", default-features = false }
alloy-json-rpc = { version = "= 1.0.35", default-features = false }
alloy-network = { version = "= 1.0.35", default-features = false }
alloy-network-primitives = { version = "= 1.0.35", default-features = false }
alloy-provider = { version = "= 1.0.35", features = ["reqwest"], default-features = false }
alloy-pubsub = { version = "= 1.0.35", default-features = false }
alloy-rpc-client = { version = "= 1.0.35", default-features = false }
alloy-rpc-types = { version = "= 1.0.35", features = ["eth"], default-features = false }
alloy-rpc-types-admin = { version = "= 1.0.35", default-features = false }
alloy-rpc-types-anvil = { version = "= 1.0.35", default-features = false }
alloy-rpc-types-beacon = { version = "= 1.0.35", default-features = false }
alloy-rpc-types-debug = { version = "= 1.0.35", default-features = false }
alloy-rpc-types-engine = { version = "= 1.0.35", default-features = false }
alloy-rpc-types-eth = { version = "= 1.0.35", default-features = false }
alloy-rpc-types-mev = { version = "= 1.0.35", default-features = false }
alloy-rpc-types-trace = { version = "= 1.0.35", default-features = false }
alloy-rpc-types-txpool = { version = "= 1.0.35", default-features = false }
alloy-serde = { version = "= 1.0.35", default-features = false }
alloy-signer = { version = "= 1.0.35", default-features = false }
alloy-signer-local = { version = "= 1.0.35", default-features = false }
alloy-transport = { version = "= 1.0.35" }
alloy-transport-http = { version = "= 1.0.35", features = ["reqwest-rustls-tls"], default-features = false }
alloy-transport-ipc = { version = "= 1.0.35", default-features = false }
alloy-transport-ws = { version = "= 1.0.35", default-features = false }

alloy-primitives = { version = "1.3.1", default-features = false, features = ["map-foldhash"] }

# Database
rusqlite = { version = "0.32", features = ["bundled", "chrono"] }

# Async and utilities
clap = { version = "4", features = ["derive"] }
eyre = "0.6"
futures = "0.3"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1.41"

# Additional utilities
lazy_static = "1.4"
hex = "0.4"
itertools = "0.10.5"

[dev-dependencies]
tempfile = "3"

[features]
default = ["jemalloc"]
jemalloc = ["dep:tikv-jemallocator"]
asm-keccak = ["reth/asm-keccak"]
min-debug-logs = ["reth/min-debug-logs"]
client = []

[dependencies.tikv-jemallocator]
version = "0.6.0"
optional = true

[profile.maxperf]
inherits = "release"
lto = "fat"
codegen-units = 1
incremental = false

[[bin]]
name = "reth"
path = "src/main.rs"

[patch.crates-io]
# reth
reth = { git = "https://github.com/0gfoundation/0g-reth", rev = "880ce24ada959d6594269c144b3b4fe8ec8aa79a" }
reth-ethereum = { git = "https://github.com/0gfoundation/0g-reth", rev = "880ce24ada959d6594269c144b3b4fe8ec8aa79a", features = ["full"] }
reth-chainspec = { git = "https://github.com/0gfoundation/0g-reth", rev = "880ce24ada959d6594269c144b3b4fe8ec8aa79a" }
reth-ethereum-cli = { git = "https://github.com/0gfoundation/0g-reth", rev = "880ce24ada959d6594269c144b3b4fe8ec8aa79a" }
reth-discv5 = { git = "https://github.com/0gfoundation/0g-reth", rev = "880ce24ada959d6594269c144b3b4fe8ec8aa79a" }
reth-execution-errors = { git = "https://github.com/0gfoundation/0g-reth", rev = "880ce24ada959d6594269c144b3b4fe8ec8aa79a" }
reth-execution-types = { git = "https://github.com/0gfoundation/0g-reth", rev = "880ce24ada959d6594269c144b3b4fe8ec8aa79a" }
reth-exex = { git = "https://github.com/0gfoundation/0g-reth", rev = "880ce24ada959d6594269c144b3b4fe8ec8aa79a", features = ["serde"] }
reth-eth-wire = { git = "https://github.com/0gfoundation/0g-reth", rev = "880ce24ada959d6594269c144b3b4fe8ec8aa79a" }
reth-evm = { git = "https://github.com/0gfoundation/0g-reth", rev = "880ce24ada959d6594269c144b3b4fe8ec8aa79a" }
reth-network = { git = "https://github.com/0gfoundation/0g-reth", rev = "880ce24ada959d6594269c144b3b4fe8ec8aa79a", features = ["test-utils"] }
reth-network-api = { git = "https://github.com/0gfoundation/0g-reth", rev = "880ce24ada959d6594269c144b3b4fe8ec8aa79a" }
reth-network-peers = { git = "https://github.com/0gfoundation/0g-reth", rev = "880ce24ada959d6594269c144b3b4fe8ec8aa79a" }
reth-node-api = { git = "https://github.com/0gfoundation/0g-reth", rev = "880ce24ada959d6594269c144b3b4fe8ec8aa79a" }
reth-node-ethereum = { git = "https://github.com/0gfoundation/0g-reth", rev = "880ce24ada959d6594269c144b3b4fe8ec8aa79a" }
reth-primitives = { git = "https://github.com/0gfoundation/0g-reth", rev = "880ce24ada959d6594269c144b3b4fe8ec8aa79a" }
# reth-primitives-traits = { git = "https://github.com/0gfoundation/0g-reth", rev = "880ce24ada959d6594269c144b3b4fe8ec8aa79a" }
reth-provider = { git = "https://github.com/0gfoundation/0g-reth", rev = "880ce24ada959d6594269c144b3b4fe8ec8aa79a" }
reth-revm = { git = "https://github.com/0gfoundation/0g-reth", rev = "880ce24ada959d6594269c144b3b4fe8ec8aa79a" }
reth-transaction-pool = { git = "https://github.com/0gfoundation/0g-reth", rev = "880ce24ada959d6594269c144b3b4fe8ec8aa79a" }
reth-tracing = { git = "https://github.com/0gfoundation/0g-reth", rev = "880ce24ada959d6594269c144b3b4fe8ec8aa79a" }

# revm
revm = { git = "https://github.com/0gfoundation/revm", rev = "6ba11f7052fa3de8aec344fd5acd952bb23b0ed7" }
revm-bytecode = { git = "https://github.com/0gfoundation/revm", rev = "6ba11f7052fa3de8aec344fd5acd952bb23b0ed7", package = "revm-bytecode" }
revm-database = { git = "https://github.com/0gfoundation/revm", rev = "6ba11f7052fa3de8aec344fd5acd952bb23b0ed7", package = "revm-database" }
revm-state = { git = "https://github.com/0gfoundation/revm", rev = "6ba11f7052fa3de8aec344fd5acd952bb23b0ed7", package = "revm-state" }
revm-primitives = { git = "https://github.com/0gfoundation/revm", rev = "6ba11f7052fa3de8aec344fd5acd952bb23b0ed7", package = "revm-primitives" }
revm-interpreter = { git = "https://github.com/0gfoundation/revm", rev = "6ba11f7052fa3de8aec344fd5acd952bb23b0ed7", package = "revm-interpreter" }
revm-inspector = { git = "https://github.com/0gfoundation/revm", rev = "6ba11f7052fa3de8aec344fd5acd952bb23b0ed7", package = "revm-inspector" }
revm-context = { git = "https://github.com/0gfoundation/revm", rev = "6ba11f7052fa3de8aec344fd5acd952bb23b0ed7", package = "revm-context" }
revm-context-interface = { git = "https://github.com/0gfoundation/revm", rev = "6ba11f7052fa3de8aec344fd5acd952bb23b0ed7", package = "revm-context-interface" }
revm-database-interface = { git = "https://github.com/0gfoundation/revm", rev = "6ba11f7052fa3de8aec344fd5acd952bb23b0ed7", package = "revm-database-interface" }
op-revm = { git = "https://github.com/0gfoundation/revm", rev = "6ba11f7052fa3de8aec344fd5acd952bb23b0ed7", package = "op-revm" }

# alloy-evm
alloy-evm = { git = "https://github.com/0gfoundation/alloy-evm", rev = "30e16f63b29ee3219413971ee08a1229499f77bd" }

# Patch alloy 1.0.35 with 0g-alloy
alloy-consensus = { git = "https://github.com/0gfoundation/0g-alloy", rev = "45168d661c4a5a3b9718ff94a2bec7f8e8e8dc1e", package = "alloy-consensus" }
alloy-contract = { git = "https://github.com/0gfoundation/0g-alloy", rev = "45168d661c4a5a3b9718ff94a2bec7f8e8e8dc1e", package = "alloy-contract" }
alloy-eips = { git = "https://github.com/0gfoundation/0g-alloy", rev = "45168d661c4a5a3b9718ff94a2bec7f8e8e8dc1e", package = "alloy-eips" }
alloy-genesis = { git = "https://github.com/0gfoundation/0g-alloy", rev = "45168d661c4a5a3b9718ff94a2bec7f8e8e8dc1e", package = "alloy-genesis" }
alloy-json-rpc = { git = "https://github.com/0gfoundation/0g-alloy", rev = "45168d661c4a5a3b9718ff94a2bec7f8e8e8dc1e", package = "alloy-json-rpc" }
alloy-network = { git = "https://github.com/0gfoundation/0g-alloy", rev = "45168d661c4a5a3b9718ff94a2bec7f8e8e8dc1e", package = "alloy-network" }
alloy-network-primitives = { git = "https://github.com/0gfoundation/0g-alloy", rev = "45168d661c4a5a3b9718ff94a2bec7f8e8e8dc1e", package = "alloy-network-primitives" }
alloy-provider = { git = "https://github.com/0gfoundation/0g-alloy", rev = "45168d661c4a5a3b9718ff94a2bec7f8e8e8dc1e", package = "alloy-provider", features = ["reqwest"] }
alloy-pubsub = { git = "https://github.com/0gfoundation/0g-alloy", rev = "45168d661c4a5a3b9718ff94a2bec7f8e8e8dc1e", package = "alloy-pubsub" }
alloy-rpc-client = { git = "https://github.com/0gfoundation/0g-alloy", rev = "45168d661c4a5a3b9718ff94a2bec7f8e8e8dc1e", package = "alloy-rpc-client" }
alloy-rpc-types ={ git = "https://github.com/0gfoundation/0g-alloy", rev = "45168d661c4a5a3b9718ff94a2bec7f8e8e8dc1e", package = "alloy-rpc-types", features = ["eth"] }
alloy-rpc-types-admin = { git = "https://github.com/0gfoundation/0g-alloy", rev = "45168d661c4a5a3b9718ff94a2bec7f8e8e8dc1e", package = "alloy-rpc-types-admin" }
alloy-rpc-types-anvil = { git = "https://github.com/0gfoundation/0g-alloy", rev = "45168d661c4a5a3b9718ff94a2bec7f8e8e8dc1e", package = "alloy-rpc-types-anvil" }
alloy-rpc-types-beacon = { git = "https://github.com/0gfoundation/0g-alloy", rev = "45168d661c4a5a3b9718ff94a2bec7f8e8e8dc1e", package = "alloy-rpc-types-beacon" }
alloy-rpc-types-debug = { git = "https://github.com/0gfoundation/0g-alloy", rev = "45168d661c4a5a3b9718ff94a2bec7f8e8e8dc1e", package = "alloy-rpc-types-debug" }
alloy-rpc-types-engine = { git = "https://github.com/0gfoundation/0g-alloy", rev = "45168d661c4a5a3b9718ff94a2bec7f8e8e8dc1e", package = "alloy-rpc-types-engine" }
alloy-rpc-types-eth = { git = "https://github.com/0gfoundation/0g-alloy", rev = "45168d661c4a5a3b9718ff94a2bec7f8e8e8dc1e", package = "alloy-rpc-types-eth" }
alloy-rpc-types-mev = { git = "https://github.com/0gfoundation/0g-alloy", rev = "45168d661c4a5a3b9718ff94a2bec7f8e8e8dc1e", package = "alloy-rpc-types-mev" }
alloy-rpc-types-trace = { git = "https://github.com/0gfoundation/0g-alloy", rev = "45168d661c4a5a3b9718ff94a2bec7f8e8e8dc1e", package = "alloy-rpc-types-trace" }
alloy-rpc-types-txpool = { git = "https://github.com/0gfoundation/0g-alloy", rev = "45168d661c4a5a3b9718ff94a2bec7f8e8e8dc1e", package = "alloy-rpc-types-txpool" }
alloy-serde = { git = "https://github.com/0gfoundation/0g-alloy", rev = "45168d661c4a5a3b9718ff94a2bec7f8e8e8dc1e", package = "alloy-serde" }
alloy-signer = { git = "https://github.com/0gfoundation/0g-alloy", rev = "45168d661c4a5a3b9718ff94a2bec7f8e8e8dc1e", package = "alloy-signer" }
alloy-signer-local = { git = "https://github.com/0gfoundation/0g-alloy", rev = "45168d661c4a5a3b9718ff94a2bec7f8e8e8dc1e", package = "alloy-signer-local" }
alloy-transport = { git = "https://github.com/0gfoundation/0g-alloy", rev = "45168d661c4a5a3b9718ff94a2bec7f8e8e8dc1e", package = "alloy-transport" }
alloy-transport-http = { git = "https://github.com/0gfoundation/0g-alloy", rev = "45168d661c4a5a3b9718ff94a2bec7f8e8e8dc1e", package = "alloy-transport-http", features = ["reqwest-rustls-tls"] }
alloy-transport-ipc = { git = "https://github.com/0gfoundation/0g-alloy", rev = "45168d661c4a5a3b9718ff94a2bec7f8e8e8dc1e", package = "alloy-transport-ipc" }
alloy-transport-ws = { git = "https://github.com/0gfoundation/0g-alloy", rev = "45168d661c4a5a3b9718ff94a2bec7f8e8e8dc1e", package = "alloy-transport-ws" }
